# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiposalimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('porcion', models.CharField(max_length=255)),
                ('tipo', models.IntegerField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Alimento_Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.Alimento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiposalimento.TipoAlimento')),
            ],
            options={
                'verbose_name': 'TiposAlimentos',
                'verbose_name_plural': 'TiposAlimentos',
            },
        ),
    ]
