# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='tipo',
        ),
    ]
